{{- if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-same-namespace
  labels:
{{ include "ccbc-metabase.labels" . | indent 4}}
spec:
  # Allow every pod from the same namespace to talk to each other
  ingress:
    - from:
        - podSelector: {}
  podSelector: {}
{{- end }}
