fullnameOverride: ccbc-metabase

metabase:
  replicaCount: 1
  image:
    repository: metabase/metabase
    pullPolicy: IfNotPresent
    tag: v0.51.3
  service:
    name: metabase
  database:
    type: postgres
    host: hippo-primary.b40eb8-dev.svc # pass in via deploy script
    port: 5432
    dbname: hippo-ha # pass in via deploy script
    username: hippo-ha # pass in via deploy script
    password: # pass in via deploy script
  resources:
    limits:
      cpu: 300m
      memory: 2Gi #TODO: update before merging to main 
    requests:
      cpu: 10m
      memory: 512Mi
  livenessProbe:
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 31
    timeoutSeconds: 3
    periodSeconds: 5

route:
  host: ccbc-metabase-dev.apps.silver.devops.gov.bc.ca # pass in via deploy script

deployer:
  serviceAccount:
    enabled: true

networkPolicies:
  enabled: true

crunchy-postgres:
  fullnameOverride: hippo-ha
  nameOverride: hippo-ha
  postgresVersion: 15
  instances:
    name: pgha1
    replicas: 1
    dataVolumeClaimSpec:
      storage: 1Gi
      storageClassName: netapp-block-standard
    requests:
      cpu: 1m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi
    replicaCertCopy:
      requests:
        cpu: 1m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
  pgBackRest:
    retention: "10" # Ideally a larger number such as 30 backups/days
    retentionFullType: count
    repos:
      schedules:
        full: 0 8 * * *
        incremental: 0 0,4,12,16,20 * * *
      volume:
        accessModes: "ReadWriteOnce"
        storage: 1Gi
        storageClassName: netapp-file-backup
    repoHost:
      requests:
        cpu: 2m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    sidecars:
      requests:
        cpu: 1m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
  pgmonitor:
    enabled: true
    exporter:
      requests:
        cpu: 1m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
  proxy:
    pgBouncer:
      replicas: 2
      requests:
        cpu: 2m
        memory: 8Mi
      limits:
        cpu: 50m
        memory: 32Mi
