fullnameOverride: ccbc-metabase



metabase:
  replicaCount: 3
  image:
    repository: metabase/metabase-enterprise
    pullPolicy: IfNotPresent
    tag: v1.44.4
  service:
    name: metabase
  database:
    type: postgres
    host: hippo-primary.b40eb8-dev.svc # pass in via deploy script
    port: 5432
    dbname: hippo-ha # pass in via deploy script
    username: hippo-ha # pass in via deploy script
    password: # pass in via deploy script

route:
  host: ccbc-metabase-dev.apps.silver.devops.gov.bc.ca # pass in via deploy script

deployer:
  serviceAccount:
    enabled: true

networkPolicies:
  enabled: true

crunchy-postgres:
  fullnameOverride: hippo-ha
  nameOverride: hippo-ha
  crunchyImage: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres:ubi8-14.7-0
  instances:
    name: pgha1
    replicas: 3
    dataVolumeClaimSpec:
      storage: 1Gi
      storageClassName: netapp-block-standard
    requests:
      cpu: 1m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi
    replicaCertCopy:
      requests:
        cpu: 1m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
  pgBackRest:
    image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest:ubi8-2.41-4
    retention: '10' # Ideally a larger number such as 30 backups/days
    retentionFullType: count
    repos:
      schedules:
        full: 0 8 * * *
        incremental: 0 0,4,12,16,20 * * *
      volume:
        accessModes: 'ReadWriteOnce'
        storage: 2Gi
        storageClassName: netapp-file-backup
    repoHost:
      requests:
        cpu: 2m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    sidecars:
      requests:
        cpu: 1m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
