metabase:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests: 
      cpu: 100m
      memory: 1Gi
crunchy-postgres:
  instances:
    dataVolumeClaimSpec:
      storage: 5Gi
  pgBackRest:
    repos:
      volume:
        storage: 8Gi
  
