# Main workflow, orchestrating and triggering other workflows
name: main

on:
  workflow_call: # be sure to use 'secrets: inherit' in the caller
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-code:
    uses: ./.github/workflows/test-code.yaml
    secrets: inherit

  deploy:
    if: github.event.ref == 'refs/heads/main'
    needs: [test-code]
    uses: ./.github/workflows/metabase-deploy.yaml
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
