name: Deploy Metabase to OpenShift

on:
  push:
    branches: [main]

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}

jobs:
  deploy-to-metabase-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: "https://ccbc-metabase-dev.apps.silver.devops.gov.bc.ca"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/metabase
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_metabase_namespace: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
          host_route: ${{ secrets.HOST_ROUTE }}
          db_route: ${{ secrets.DB_ROUTE }}
          db_password: ${{ secrets.DB_PASSWORD }}

  deploy-to-metabase-test:
    needs: [deploy-to-metabase-development]
    runs-on: ubuntu-latest
    environment:
      name: test
      url: "https://ccbc-metabase-test.apps.silver.devops.gov.bc.ca"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/metabase
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_metabase_namespace: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
          host_route: ${{ secrets.HOST_ROUTE }}
          db_route: ${{ secrets.DB_ROUTE }}
          db_password: ${{ secrets.DB_PASSWORD }}

  deploy-to-metabase-production:
    needs: [deploy-to-metabase-test]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://ccbc-metabase.apps.silver.devops.gov.bc.ca"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/metabase
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_metabase_namespace: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
          host_route: ${{ secrets.HOST_ROUTE }}
          db_route: ${{ secrets.DB_ROUTE }}
          db_password: ${{ secrets.DB_PASSWORD }}
